### ISSUE TITLE
Change name for ration and autarky

### ISSUE THREAD

**Issue by leinich** [JonahKr/power-distribution-card#10]
Thanks a lot for this great lovelace card.

If I'm reading the code correctly the words ratio and autarky is currently hardwritten:
https://github.com/JonahKr/power-distribution-card/blob/64d8f3f677d5ce12cfd57e59b66b5e4a2b344a5d/src/power-distribution-card.ts#L143

Could you add a possibilty to change this via name attribute?

```
// works
home: 
  entity: sensor.e3dc_house_power
  invert_arrow: true
  name: Haus
// don't work
autarky:
  entity: sensor.e3dc_autarki
  name: Autarkie
```
