### ISSUE TITLE
'autarky' and 'ratio' not being calculated

### ISSUE THREAD

**Issue by brhahlen** [JonahKr/power-distribution-card#102]
Hello!
Like the card, has the nice clean look that I like!

However, my `autarky` and `ratio` are not being calculated for some reason.

This is my setup:
```
type: custom:power-distribution-card
title: ''
entities:
  - decimals: 2
    display_abs: true
    name: home
    unit_of_display: adaptive
    unit_of_measurement: kW
    consumer: true
    icon: mdi:home-assistant
    entity: sensor.power_consumed
    preset: home
  - decimals: 2
    display_abs: true
    name: solar
    icon: mdi:solar-power
    producer: true
    entity: sensor.qmb392011c_output_power
    preset: solar
  - decimals: 2
    display_abs: true
    name: grid
    icon: mdi:transmission-tower
    entity: sensor.current_power_usage_calc
    preset: grid
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
animation: flash
```

And this is the output:
![image](https://user-images.githubusercontent.com/1798663/154264746-9b28656c-b25b-4ec8-a155-0032f9fd699a.png)

Am I missing something?
