### ISSUE TITLE
Disappeared

### ISSUE THREAD

**Issue by mdeakin99** [JonahKr/power-distribution-card#143]
About a week or so ago,  this card disappeared from a few different locations within Home Assistant.  I have checked the 'Raw Configuration Editor' and can see the card is still mentioned in the code,  it just doesn't display anymore.

If I re-add the card manually it displays.

**Comment by JonahKr** [comment]
Can you check if there is an errror in the web console?
Since i cannot reproduce this, it is a bit difficult for me to find out what causes this 🤔 

The only thing similar i've ever encountered is during development when i have to force clear the cache very frequently.

**Comment by mdeakin99** [comment]
I presume as part of the reinstall the code in your dashboard stayed there so it just started appearing again.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Saentist** [comment]
Is anybody see strange behaviour in YAML config when the visualization disappear?

Nothing show ( marked strange lines)
```yaml
type: custom:power-distribution-card
title: Power eater
entities:
  config:  <¹
    - decimals: 2 <² 
      display_abs: true
      name: grid
      unit_of_display: W
      icon: mdi:transmission-tower
      entity: sensor.clamp_meter_power_2 #<³
      preset: grid
      icon_color:
        equal: '700'
        bigger: '100'
        smaller: '200'
      secondary_info_entity: sensor.clamp_meter_current_2
    - decimals: 2 #<² 
      display_abs: true
      name: Growatt
      unit_of_display: W
      icon: mdi:solar-power-variant-outline
      producer: true
      entity: sensor.frj7cht0nz_output_power  #<³
      preset: solar
      secondary_info_entity: sensor.frj7cht0nz_input_1_amperage
    - decimals: 2 #<² 
      display_abs: true
      name: forecast
      unit_of_display: W
      producer: true
      entity: sensor.power_production_now #<³
      preset: solar
      secondary_info_entity: sensor.openweathermap_cloud_coverage
      icon: mdi:solar-power-variant
      calc_excluded: true
    - decimals: '2'  #<² 
      display_abs: true
      name: Fridge
      unit_of_display: W
      consumer: true
      icon: mdi:fridge
      entity: sensor.wifi_plug_2_98b0_power #<³
      preset: consumer
      icon_color:
        bigger: orange
        equal: red
      secondary_info_entity: sensor.sp2_amp
      invert_value: true
    - decimals: 2 #<² 
      display_abs: true
      name: APC-vmware
      unit_of_display: W
      consumer: true
      icon: mdi:server-network
      entity: sensor.smartplug3_power #<³
      preset: consumer
      invert_value: true
    - decimals: '2' <² 
      display_abs: true
      name: Нощна лампа
      unit_of_display: W
      consumer: true
      icon: mdi:lightbulb
      entity: sensor.wifi_plug_4_56d0_power #<³
      preset: consumer
      icon_color:
        bigger: orange
        equal: red
      secondary_info_entity: sensor.sp4_amp
      invert_value: true
    - decimals: '2' #<² 
      display_abs: true
      name: Fujitsu
      unit_of_display: W
      consumer: true
      icon: mdi:desktop-classic
      entity: sensor.wifi_plug_5_b132_power #<³
      preset: consumer
      icon_color:
        bigger: orange
        equal: red
        smaller: green
      secondary_info_entity: sensor.sw5_amp
      invert_value: true
    - decimals: '2' #<² 
      display_abs: true
      name: SP6 конвектор
      unit_of_display: W
      consumer: true
      icon: mdi:lightbulb
      entity: sensor.wifi_plug_6_555b_power #<³
      preset: consumer
      icon_color:
        bigger: orange
        equal: red
      secondary_info_entity: sensor.sp5_amp
      invert_value: true
      color_threshold: '0'
    - decimals: '2' #<² 
      display_abs: true
      name: LG ThermaV
      unit_of_display: W
      consumer: true
      icon: mdi:lightbulb
      entity: sensor.power #<³
      preset: consumer
      icon_color:
        bigger: orange
        equal: green
        smaller: blue
      secondary_info_entity: sensor.current
      invert_value: true
      arrow_color:
        bigger: '100'
        equal: '60'
        smaller: '50'
    - decimals: '2' #<² 
      display_abs: true
      name: battery
      unit_of_display: '%'
      consumer: true
      icon: mdi:battery-90
      producer: true
      entity: sensor.ups_battery #<³
      preset: battery
      icon_color:
        bigger: green
      calc_excluded: true
      invert_value: true
    - decimals: 2 #<² 
      display_abs: true
      name: consumer
      unit_of_display: W
      consumer: true
      icon: mdi:fan
      entity: sensor.watt #<³
      preset: consumer
      invert_value: true
      secondary_info_entity: sensor.current_2
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
    - name: Cloud
      preset: ratio
      entity: sensor.openweathermap_cloud_coverage #<³
animation: slide
```

¹ never before see this
² "decimals: 2 " or "decimals: '2' "  why there is a "-" before?
³  why there is no "-" before?
"display_abs: true" where this come from?
some other wired formatting.
removed an rearranged some lines.
used https://www.yamllint.com to validate yaml code

working code
```yaml
type: custom:power-distribution-card
title: Power eater
entities:
  - entity: sensor.clamp_meter_power_2
    name: grid
    unit_of_display: W
    icon: mdi:transmission-tower
    preset: grid
    icon_color:
      equal: "700"
      bigger: "100"
      smaller: "200"
    secondary_info_entity: sensor.clamp_meter_current_2
  - entity: sensor.frj7cht0nz_output_power
    name: Growatt
    unit_of_display: W
    icon: mdi:solar-power-variant-outline
    producer: true
    preset: solar
    secondary_info_entity: sensor.frj7cht0nz_input_1_amperage
  - entity: sensor.power_production_now
    name: forecast
    unit_of_display: W
    producer: true
    preset: solar
    secondary_info_entity: sensor.openweathermap_cloud_coverage
    icon: mdi:solar-power-variant
    calc_excluded: true
  - entity: sensor.wifi_plug_2_98b0_power
    name: Fridge
    unit_of_display: W
    consumer: true
    preset: consumer
    icon_color:
      bigger: orange
      equal: red
    secondary_info_entity: sensor.sp2_amp
    invert_value: true
  - entity: sensor.smartplug3_power
    name: APC-vmware
    unit_of_display: W
    consumer: true
    icon: mdi:server-network
    preset: consumer
    invert_value: true
  - entity: sensor.wifi_plug_4_56d0_power
    name: Нощна лампа
    unit_of_display: W
    consumer: true
    icon: mdi:lightbulb
    preset: consumer
    icon_color:
      bigger: orange
      equal: red
    secondary_info_entity: sensor.sp4_amp
    invert_value: true
  - entity: sensor.wifi_plug_5_b132_power
    name: Fujitsu
    unit_of_display: W
    consumer: true
    icon: mdi:desktop-classic
    preset: consumer
    icon_color:
      bigger: orange
      equal: red
      smaller: green
    secondary_info_entity: sensor.sw5_amp
    invert_value: true
  - entity: sensor.wifi_plug_6_555b_power
    name: SP6 конвектор
    unit_of_display: W
    consumer: true
    icon: mdi:lightbulb
    preset: consumer
    icon_color:
      bigger: orange
      equal: red
    secondary_info_entity: sensor.sp5_amp
    invert_value: true
    color_threshold: "0"
  - entity: sensor.power
    name: LG ThermaV
    unit_of_display: W
    consumer: true
    icon: mdi:lightbulb
    preset: consumer
    icon_color:
      bigger: orange
      equal: green
      smaller: blue
    secondary_info_entity: sensor.current
    invert_value: true
    arrow_color:
      bigger: "100"
      equal: "60"
      smaller: "50"
  - entity: sensor.ups_battery
    name: battery
    unit_of_display: "%"
    consumer: true
    icon: mdi:battery-90
    producer: true
    preset: battery
    icon_color:
      bigger: green
    calc_excluded: true
    invert_value: true
  - entity: sensor.watt
    name: consumer
    unit_of_display: W
    consumer: true
    icon: mdi:fan
    preset: consumer
    invert_value: true
    secondary_info_entity: sensor.current_2
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
    - name: Cloud
      preset: ratio
      entity: sensor.openweathermap_cloud_coverage
animation: slide
```

@JonahKr what can be strange problem to broke yaml formatting?
