### ISSUE TITLE
Need help with verification

### ISSUE THREAD

**Issue by schumissimo63** [JonahKr/power-distribution-card#158]
Hello, I am coming back to you for confirmation or a correction that the formatting of my sound cards is correct, I am sharing my codes with you. I am asking you this because the data displayed does not correspond to the data in the home assistant energy table.
Thanking you in advance.

![2023-12-22_153930](https://github.com/JonahKr/power-distribution-card/assets/76776295/930f262a-8159-4270-8fe8-7dcb3104a0f0)

```
type: custom:power-distribution-card
title: CONSO JOUR
entities:
  - decimals: 2
    display_abs: true
    name: Maison
    unit_of_display: kWh
    consumer: true
    icon: mdi:home
    entity: sensor.conso_energie_jour
    preset: consumer
    invert_value: true
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Import
    unit_of_display: kWh
    icon: mdi:transmission-tower
    entity: sensor.energie_importee_jour
    preset: consumer
    invert_value: false
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Solaire
    unit_of_display: kWh
    icon: mdi:solar-power
    producer: true
    entity: sensor.prod_solaire_jour
    preset: solar
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Export
    unit_of_display: kWh
    icon: mdi:lightning-bolt-outline
    consumer: true
    entity: sensor.energie_exportee_jour
    preset: consumer
    calc_excluded: false
    invert_value: true
center:
  type: bars
  content:
    - preset: autarky
      name: AS
      bar_color: red
    - preset: ratio
      name: Ratio
      bar_color: green
animation: flash
```

```
type: custom:power-distribution-card
title: CONSO LIVE
entities:
  - decimals: 2
    display_abs: true
    name: Maison
    unit_of_display: W
    consumer: true
    icon: mdi:home
    entity: sensor.envoy_122243083234_current_power_consumption
    preset: consumer
    invert_value: true
    icon_color:
      bigger: green
      equal: blue
      smaller: red
    arrow_color:
      bigger: green
      equal: blue
      smaller: red
  - decimals: 2
    display_abs: true
    name: Import
    unit_of_display: w
    icon: mdi:transmission-tower
    entity: sensor.energie_importee
    preset: grid
    invert_value: true
    calc_excluded: false
    icon_color:
      bigger: green
      equal: blue
      smaller: red
    arrow_color:
      bigger: green
      equal: blue
      smaller: red
  - decimals: 2
    display_abs: false
    name: Solaire
    unit_of_display: w
    icon: mdi:solar-power
    producer: true
    entity: sensor.envoy_122243083234_current_power_production
    preset: solar
    calc_excluded: false
    icon_color:
      bigger: green
      equal: blue
      smaller: red
    arrow_color:
      bigger: green
      equal: blue
      smaller: red
    color_threshold: '-8'
  - decimals: 2
    display_abs: true
    name: Export
    unit_of_display: w
    icon: mdi:lightning-bolt-outline
    producer: true
    entity: sensor.energie_exportee
    preset: grid
    calc_excluded: false
    invert_value: true
    icon_color:
      equal: blue
      bigger: green
      smaller: red
    arrow_color:
      equal: blue
      bigger: green
      smaller: red
center:
  type: bars
  content:
    - preset: autarky
      name: AS
      bar_color: red
    - preset: ratio
      name: Ratio
      bar_color: green
animation: flash
```
