### ISSUE TITLE
use picture in center

### ISSUE THREAD

**Issue by thamesseb2** [JonahKr/power-distribution-card#161]
hi 
im trying to add a picture in center
like:

center:
  type: card
  content:
    type: picture
    image: /local/foto-pkg/zcs.png

but this give me custom element don't exist, is a bug or i worong something?

**Comment by neotigger** [comment]
Definitely not a bug.
![Bildschirmfoto 7](https://github.com/JonahKr/power-distribution-card/assets/121525065/1f13576c-1fcf-4df7-97ff-7cd66716dc24)

**Comment by thamesseb2** [comment]
![image](https://github.com/JonahKr/power-distribution-card/assets/125477524/80f6d527-c459-433c-a8f1-443e62aef26e)
so probably i wrong something

**Comment by neotigger** [comment]
I have to correct myself. For example, the card alone on a dashboard, the error occurs.
Together with other cards, it works
![Bildschirmfoto 8](https://github.com/JonahKr/power-distribution-card/assets/121525065/d07ed52d-7681-4308-b3dd-916c3da4255c)
![Bildschirmfoto 9](https://github.com/JonahKr/power-distribution-card/assets/121525065/9f226d61-c9be-4dfa-99d5-1857bc026a46)

**Comment by thamesseb2** [comment]
Thank goodness, I was going crazy :D

**Comment by buanet** [comment]
Can confirm this. If I use the picture card in center I get the same error.
When you add a the same picture as a standalone picture card on the same dashboard it works. 

Using a picture-entity card instead seems to work for me.

```
center:
  type: card
  content:
    type: picture-entity
    image: /local/s10.png
    entity: [some.dummy.entity]
    show_state: false
    show_name: false
    camera_view: auto
    tap_action:
      action: none
    hold_action:
      action: none
```

regards,
André
