### ISSUE TITLE
Color threshold not working when using invert_arrows

### ISSUE THREAD

**Issue by ErikT80** [JonahKr/power-distribution-card#168]
First of all thanks for the amazing card! Been using it for years with pleaure. I noticed today when adding a new entity that the color threshold is not working when using invert_arrows:

This works and shows the icon red when power is higher then 7 W.

```
- decimals: "0"
   display_abs: true
   name: Heatpump
   unit_of_display: W
   consumer: true
   icon: mdi:heat-pump-outline
   entity: sensor.heatpump_power
   preset: consumer
   threshold: ""
   icon_color:
       equal: ""
       smaller: ""
       bigger: "red"
   hide_arrows: false
   calc_excluded: true
   color_threshold: "7"
```

This doesn't work (icon is regular color)

```
- decimals: "0"
   display_abs: true
   name: Heatpump
   unit_of_display: W
   consumer: true
   icon: mdi:heat-pump-outline
   entity: sensor.heatpump_power
   preset: consumer
   threshold: ""
   icon_color:
       equal: ""
       smaller: ""
       bigger: "red"
   hide_arrows: false
   calc_excluded: true
   color_threshold: "7"
   invert_arrows: true
```
