### ISSUE TITLE
Power in KW

### ISSUE THREAD

**Issue by sebasptsch** [JonahKr/power-distribution-card#17]
Implement a way to change the rounding of the values or set the entity values to kW instead of W. The use case is the Tesla Powerwall.

**Comment by JonahKr** [comment]
The question here is whether the values come in in kW or in W.
You will be able to change the unit of measurement from. 1.5 on, however this doesn't have a direct effect on the value.

**Comment by sebasptsch** [comment]
Ok, the issue is that at the moment the card is rounding and, as a result the amount of arrows don't change because it's such a "small" number. Though the kilowatt reading has 3 decimal places of accuracy.

Thanks for addressing this.

**Comment by JonahKr** [comment]
This should be fairly simple to implement but I am wondering how this should work on the configuration.
My idea was to create a 'incoming_unit' setting for entities which accepts only 2 variables for now ( W and kw) and then it will be converted to watts to do the internal handling.
I assume you want to display it as kW aswell right?

**Comment by sebasptsch** [comment]
Originally I was just thinking to convert all the values from kW to W.

**Comment by JonahKr** [comment]
Maybe I can get ahold of the sensor unit of measurement directly from Hass. Will have to further investigate...

**Comment by JonahKr** [comment]
Ok it is possible. however not in a really nice way. For now i will implement a option to set the incoming value unit which will handle the rest. I want to get 1.5 out until tomorrow. 
I will try to implement this afterwards in a nicer way, but temporarily this should be fine.

**Comment by JonahKr** [comment]
Added in https://github.com/JonahKr/power-distribution-card/commit/169f62c83f03a517f9849a9811ef80c056322364
It should detect the `unit_of_measurement` of your sensor automatically and adjust the value.
I tried it with a custom sensor but i cannot replicate your environment to 100%.
I would be grateful for Feedback though.

**Comment by sebasptsch** [comment]
Getting this error now on the dev branch built on my machine.
```yaml
t.entities is undefined

type: 'custom:power-distribution-card'
title: Overview
battery:
  entity: sensor.powerwall_battery_now
  invert_value: false
home:
  entity: sensor.powerwall_load_now
  invert_value: false
solar: sensor.powerwall_solar_now
grid:
  entity: sensor.powerwall_site_now
  invert_value: true
```
