### ISSUE TITLE
Invert value have no effect

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#20]
I just updated to the new version.

From the enclosed jpg, it can be seen that invert value on the home sensor have no effect.
Value is positive, as can be seen in the graph below, as well as the entity card for sensor.energy_consumption

![power-distribution-card](https://user-images.githubusercontent.com/3110308/95653018-a7001d80-0af5-11eb-8367-9625bc7b4bd9.JPG)

**Comment by JonahKr** [comment]
@pesor  So the settings work the same as in 1.4... 
If you want to set more then just the entity_id, you'll need to set the entity setting.
In yaml sadly its not possible to read the string behind the preset and the subsettings.

And watch out regarding indentation.
```yaml
type: 'custom:power-distribution-card'
title: Overview
entities:
  - solar: sensor.fronius_pac
  - grid: sensor.fronius_energy_grid
  - home:
      entity: sensor.energy_consumption
      invert-value: true
```
