### ISSUE TITLE
How I have used your card

### ISSUE THREAD

**Issue by pesor** [JonahKr/power-distribution-card#25]
This is actually not an issue, but an example for how I have used your card:

![overview](https://user-images.githubusercontent.com/3110308/96091266-ab4b8280-0ec9-11eb-8f95-1af8f73c7bd0.JPG)

I changed the green column to show how much of production goes to grid, and blue, shoe how much of my production goes to own energy consumption.

(actually a nice feature would be to have an third column showing how much of the total consumption comes from the grid)

This is the coding in the power-distribution-card:
```yaml
type: 'custom:power-distribution-card'
title: Overview
entities:
  - solar: sensor.fronius_pac
  - grid: sensor.fronius_energy_grid
  - home:
      entity: sensor.energy_consumption
      invert_value: true
  - autarky:
      bar_color: blue
      name: Eget
  - ratio:
      entity: sensor.fronius_w_to_grid
      bar_color: green
      name: t/Grid
```
and this is the coding in the configuration.yaml, where I have made som work variables:

#START Fronius and Kamstrup variables
# calculate energy consumption
```yaml
  - platform: template
    sensors:
      energy_consumption:
        value_template: >
            {{'%0.0f' | format(states('sensor.fronius_pac') | float - 
                       states('sensor.kamstrup_activepowerminus') | float + 
                       states('sensor.kamstrup_activepowerplus') | float) }}
        unit_of_measurement: 'W'
```

# Energy consumption must not be negative
```yaml
  - platform: template
    sensors:
      fronius_energy_consumption:
        value_template: >
              {% if states('sensor.energy_consumption')|float < 0 %} 0
              {% endif %}        
        unit_of_measurement: 'W'
```

# compute grid
```yaml
  - platform: template
    sensors:
      fronius_energy_grid:
        value_template: >
            {{'%0.0f' | format(states('sensor.energy_consumption') | float - states('sensor.fronius_pac') | float) }}
        unit_of_measurement: 'W'
```

# calculate to grid 
```yaml
  - platform: template
    sensors:
      fronius_w_to_grid:
        value_template: >
          {% set grid = states('sensor.fronius_energy_grid') %}
          {% set prod = states('sensor.fronius_pac') %}  
          {% set result = grid |float / prod |float *-1 %}
          {% if result |float < 0.00 %} 0
          {% elif result |float > 0.00 %}
             {{ '% 0.0f' | format(states('sensor.fronius_energy_grid') | float /  states('sensor.fronius_pac') | float *-100) }}
          {% else %} 0
          {% endif %}    
```

# END Fronius & Kamstrup

Thanks for a very good card.
