### ISSUE TITLE
Invert arrow not working

### ISSUE THREAD

**Issue by jeblond** [JonahKr/power-distribution-card#28]
Invert arrow is not working. No matter how i set it up ( true or false ) it always show current going out of my battery.

**Comment by JonahKr** [comment]
Will need to further investigate 👍

**Comment by jeblond** [comment]
Also invert value, name are not working :)

**Comment by JonahKr** [comment]
ok then there is a problem on your side.... Can you tell me which version you are running?

**Comment by jeblond** [comment]
i selected master in HACS

**Comment by JonahKr** [comment]
I would need your configuration aswell.. It seems like you configured something wrong.

**Comment by jeblond** [comment]
![github](https://user-images.githubusercontent.com/20698520/96700907-a50d4880-1398-11eb-87a8-4cb8ccb09d8c.jpg)

**Comment by JonahKr** [comment]
Yes. so when changing a Preset to advanced setup, you can nolonger pass the entity_id directly and you need to create a entity setting. I haven't figured out yet on how i could make it working this way....

A correct yaml would be:
```yaml
cards:
  - type: 'custom:power-distribution-card'
    entities:
      - solar:
          entity: sensor.pvwatts
          name: Solar
      - grid: 
          entity: sensor.modbuswatts
          name: Grid
      - battery:
          entity: sensor.batteryenergy
          invert_value: true
          name: Battery
      - home:
          entity: sensor.houseload
```
I have seen this misunderstanding quite often now so i will look into how to prevent it in the future...
Take Care 👍
