### ISSUE TITLE
2 sensors for the grid

### ISSUE THREAD

**Issue by Cereal2nd** [JonahKr/power-distribution-card#36]
Hi, in my setup i have 2 different sensors that define the grid:

- sensor.power_consumption
- sensor.power_production

how would i use this card with the 2 sensors?

**Comment by JonahKr** [comment]
Hey @Cereal2nd 👋 
So i assume that the first one is for the power pulled from the grid and the later ist for power supplied to the grid. Atm there unfortunately isn't a option for this to solve it with one item. I could look into on what would be agood way to implement it but i have quite alot to do atm regarding the visual editor.

One option for you might be setting up 2 different items:
```yaml
entities:
  - grid:
      entity: sensor.power_consumption
  - consumer:
      entity: sensor.power_production
      invert-value: true
      icon: mdi:transmission-tower
      name: grid
```
If however power consumption is the power consumption of the house, then it would just be:
```yaml
entities:
  - grid:
      entity: sensor.power_production
  - home:
      entity: sensor.power_consumption
      invert-value: true
```

If you can give me more specific info i could look into a better way.

**Comment by Cereal2nd** [comment]
This solution i used for the last couple of days, but thats not the real solution.

sensor.power_consumption = the value we pull from the grid, if the house is using grid power, in this case sensor.power_production will always be 0

if we deliver to the grid
sensor.power_consumption will always be 0
sensor.power_production will the value we deliver to the grid

so the value used for th grid would be:
sensor.power_production - sensor.power_consumption

**Comment by JonahKr** [comment]
Good Evening @Cereal2nd ,
Just to give you a update. I thought about it and it kinda is a edge case and i don't have the time to implement it for now. If more people raise this issue, i will of course reconsider this.
I can however offer you a quick fix using template_sensors
```yaml
sensor:
  - platform: template
    sensors:
      power_home:
        unit_of_measurement: 'W'
        value_template: >-
          {% set consumption = states('sensor.power_consumption') |int %}
          {% if consumption > 0 %} {{ consumption * -1 }}
          {% else %} {{ states('sensor.power_production') }}
          {% endif %}
```
Take Care! 👍
