### ISSUE TITLE
Cannot change autarky and ratio color and name

### ISSUE THREAD

**Issue by jvunc** [JonahKr/power-distribution-card#40]
Hi, Great card 
I have just a problem for changing name ( still autarky and ratio) and color (always grey)
Any issue about that ?

![UI view - Home Assistant - Google Chrome](https://user-images.githubusercontent.com/30327475/102856404-7dab2880-447a-11eb-9a35-dbd4ccc57b3c.jpg)
![UI view - Home Assistant - Google Chrome_2](https://user-images.githubusercontent.com/30327475/102856418-8a2f8100-447a-11eb-97e1-5de40793574d.jpg)

**Comment by JonahKr** [comment]
Hi there @jvunc  👋 
I know that the card gets more and more messy with all the new features. So Aktually you can expect a Visual Editor in the next release. Anyways here is the corrected version of your config:
```yaml
center:
  - ratio:
      name: Auto
      bar_color: red
      entity: sensor.e3dc_ratio
  - autarky:
      name: Prod
      bar_color: '#F0F967'
      entity: sensor.e3dc_ratio
```
Ofc you would need to change your sensors.
Anyways take care 👍

**Comment by jvunc** [comment]
Hi again
Tried as expected but no change.
I don't know also why Hom Assistant always add 'null' beside autarky and ratio

here is the card config:

`
type: 'custom:power-distribution-card'
title: My Power Card with Shelly 2 OK
animation: slide
center:
  - ratio: null
    name: Auto
    bar_color: red
    entity: sensor.solar_shem_energy_autoprod_daily_kwh
  - autarky: null
    name: Prod
    bar_color: '#F0F967'
    entity: sensor.solar_shem_energy_autoconso_daily_kwh
entities:
  - solar: sensor.solarenvoy_current_energy_production
  - grid: sensor.diff_conso_prod_solaire_courant_watts
  - home: sensor.solarenvoy_current_energy_consumption_negative

`
This config don't work.
Thanks if you can provide help.

jvunc

**Comment by jvunc** [comment]
in addition
Home Assisant is running Operating System 5.9

**Comment by JonahKr** [comment]
Please Watch out for indentation.
there is a tab for every element under Autarky/ratio
```yaml
center:
  - ratio:
      name: Auto
```
Look at `name` - Its indented one unit further

**Comment by JonahKr** [comment]
@jvunc  try this
```yaml
center:
  - ratio:
      name: Prod
      bar_color: red
      entity: sensor.solar_shem_energy_autoprod_daily_kwh
  - autarky:
      name: Cons
      bar_color: '#F0F967'
      entity: sensor.solar_shem_energy_autoconso_daily_kwh
```
