### ISSUE TITLE
v2.0 - My Card Stopped Working | Visual Editor doesn't work

### ISSUE THREAD

**Issue by JonahKr** [JonahKr/power-distribution-card#41]
Hey there 👋 
I am very sorry that updating this card disabled your configured settings.
Adding the Visual Editor required some serious changes to how configuration is handled and therefore quite a few breaking changes had to be introduced.
This will be the Last time though. *I hope*

If you still have issues getting everything back working feel free to post it in this thread and i will help you as fast as possible.

**Comment by robertklep** [comment]
Is it at all possible to use v2.0 when running Lovelace in YAML mode?

**Comment by JonahKr** [comment]
@robertklep afaik this should work fine. it might be a bit of a pain to configure though. I will expand the documentation to make this easier.
I will just post a demo configuration here for now: 
```yaml
type: 'custom:power-distribution'
title: Power
entities:
  - decimals: '2'
    display_abs: true
    name: home
    unit_of_display: A
    consumer: true
    icon: 'mdi:home-assistant'
    entity: sensor.demo_home
    preset: home
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: false
  - decimals: 2
    display_abs: true
    name: grid
    unit_of_display: W
    icon: 'mdi:transmission-tower'
    entity: sensor.demo_grid
    preset: grid
  - decimals: 2
    display_abs: true
    name: solar
    unit_of_display: W
    icon: 'mdi:solar-power'
    producer: true
    entity: sensor.demo_solar
    preset: solar
  - decimals: 2
    display_abs: true
    name: battery
    unit_of_display: W
    consumer: true
    icon: 'mdi:battery-outline'
    producer: true
    entity: sensor.demo_battery
    preset: battery
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
animation: flash
```

You don't need to configure everything as there is a fallback for most settings but especially the preset has to be defined for every entity.

**Comment by robertklep** [comment]
I don't mind it being a pain, otherwise I wouldn't have chosen for YAML mode at all 😉

With your instructions I was able to update my previous configuration so I'm happy again! 🥳

**Comment by codedmind** [comment]
Trying the v2 today... using the gui the ratio and autarky don't change... missing something?
![Screenshot 2020-12-28 at 15 28 27](https://user-images.githubusercontent.com/2910047/103225247-6c05cd00-4921-11eb-8f9b-fd550f32bc2f.png)

**Comment by JonahKr** [comment]
@codedmind  thats wierd... for me that works... do you mind posting your code-config here?

**Comment by codedmind** [comment]
@JonahKr yes i can..

type: 'custom:power-distribution-card'
title: Title
entities:
  - decimals: '2'
    display_abs: true
    name: grid
    unit_of_display: W
    icon: 'mdi:transmission-tower'
    entity: sensor.enphaseenvoy_importing
    preset: grid
    icon_color:
      bigger: red
      equal: ''
      smaller: green
    calc_excluded: true
  - decimals: '2'
    display_abs: true
    name: solar
    unit_of_display: W
    icon: 'mdi:solar-power'
    producer: true
    entity: sensor.enphaseenvoy_current_energy_production
    preset: solar
    icon_color:
      bigger: green
      equal: yellow
      smaller: red

**Comment by JonahKr** [comment]
@codedmind so i dug thorugh your configuration and your `home` seems to be configured wrongly... since you ticked the calc-excluded Checkbox there is no way to calculate neither autarky nor the ratio. 
 
 ```yaml
   - decimals: '2'
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: 'mdi:home-assistant'
    entity: sensor.house_power_consumption
    preset: home
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: true
    calc_excluded: false
    ```
    
    If you replace your home config with this, this should get you some results.

**Comment by codedmind** [comment]
@JonahKr sorry, was wrong paste, i try that when nothing happen... The i try put and remove some checkbox to see if something work :(

**Comment by JonahKr** [comment]
@codedmind  ok i am going to delete this message once you react with something here. If you want, i can help you via discord to get this working. i am kind of intruiged in it myself. `Jonah#6252`
If you don't want to do that, i would need a image from your card atm with the config applied to it. Just go to the Codeeditor and screenshot the important parts side by side.

**Comment by codedmind** [comment]
@JonahKr  Start from scrach

```

entities:
  - decimals: 2
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: 'mdi:home-assistant'
    entity: sensor.house_power_consumption
    preset: home
  - decimals: 2
    display_abs: true
    name: grid
    unit_of_display: W
    icon: 'mdi:transmission-tower'
    entity: sensor.enphaseenvoy_energy_grid
    preset: grid
  - decimals: 2
    display_abs: true
    name: solar
    unit_of_display: W
    icon: 'mdi:solar-power'
    producer: true
    entity: sensor.enphaseenvoy_current_energy_production
    preset: solar
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
animation: flash
```

**Comment by JonahKr** [comment]
@codedmind  try checking the invert-value Checkbox for your home.
or just:
```yaml
entities:
  - decimals: 2
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: 'mdi:home-assistant'
    entity: sensor.house_power_consumption
    preset: home
    invert_value: true
  - decimals: 2
    display_abs: true
    name: grid
    unit_of_display: W
    icon: 'mdi:transmission-tower'
    entity: sensor.enphaseenvoy_energy_grid
    preset: grid
  - decimals: 2
    display_abs: true
    name: solar
    unit_of_display: W
    icon: 'mdi:solar-power'
    producer: true
    entity: sensor.enphaseenvoy_current_energy_production
    preset: solar
center:
  type: bars
  content:
    - preset: autarky
      name: autarky
    - preset: ratio
      name: ratio
animation: flash
```
