### ISSUE TITLE
Center cards are redrawn on each render

### ISSUE THREAD

**Issue by z8i** [JonahKr/power-distribution-card#48]
Hello! I really enjoy the power distribution card and use it with an E3DC-System.
Now I tried to configure two gauge-cards as a vertical stack in the middle, this basically works, but the cards get redrawn like every other second. This looks somehow weird...

https://user-images.githubusercontent.com/37486180/104063963-62bc1080-51fd-11eb-924c-32f40e6e7f7e.mp4

My code:

```yaml
      - type: 'custom:power-distribution-card'
        title: ''
        entities:
          - decimals: 2
            display_abs: true
            name: solar
            unit_of_display: W
            icon: 'mdi:solar-power'
            producer: true
            entity: sensor.e3dc_pv_leistung
            preset: solar
          - decimals: 2
            display_abs: true
            name: grid
            unit_of_display: W
            icon: 'mdi:transmission-tower'
            entity: sensor.e3dc_netzleistung
            preset: grid
          - decimals: 2
            display_abs: true
            name: battery
            unit_of_display: W
            consumer: true
            icon: 'mdi:battery-outline'
            producer: true
            entity: sensor.e3dc_batterieleistung
            preset: battery
          - decimals: 2
            display_abs: true
            name: home
            unit_of_display: W
            consumer: true
            icon: 'mdi:home-assistant'
            entity: sensor.e3dc_hausleistung
            preset: home
        center:
          type: card
          content:
            type: vertical-stack
            cards:
              - type: gauge
                entity: sensor.e3dc_batterieladung
                min: 0
                max: 100
                name: Speicher
                severity:
                  green: 20
                  yellow: 10
                  red: 0
              - type: gauge
                entity: sensor.e3dc_autarkie
                min: 0
                max: 100
                name: Autarkie
                severity:
                  green: 85
                  yellow: 50
                  red: 0
        animation: slide
```

Is this caused by my configuration?
