### ISSUE TITLE
iOS App crashes with this card enabled

### ISSUE THREAD

**Issue by whizkid79** [JonahKr/power-distribution-card#56]
Hi,
first of all, thanks for this very nice card!
If I open it on my desktop, everything works fine. But if I open it with the iOS App, it only shows the menu bar without entries and after some time it loads the main view again. If I open the url in Safari on the phone, it is the same behaviour and the browser crashes after some time. Any advice?

My configuration is:
```
type: 'custom:power-distribution-card'
title: E3DC S10 pro
entities:
  - decimals: '2'
    display_abs: true
    name: solar
    unit_of_display: W
    icon: 'mdi:white-balance-sunny'
    producer: true
    entity: sensor.e3dc_solar_power
    preset: solar
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
  - decimals: 2
    display_abs: true
    name: grid
    unit_of_display: W
    icon: 'mdi:transmission-tower'
    entity: sensor.e3dc_grid_power
    preset: grid
  - decimals: '2'
    display_abs: true
    name: battery
    unit_of_display: W
    consumer: true
    icon: 'mdi:battery-outline'
    producer: true
    entity: sensor.e3dc_battery_power
    preset: battery
    icon_color:
      bigger: red
      equal: ''
      smaller: green
    invert_value: true
  - decimals: '2'
    display_abs: true
    name: home
    unit_of_display: W
    consumer: true
    icon: 'mdi:home'
    entity: sensor.e3dc_power_consumption
    preset: home
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: true
center:
  type: card
  content:
    type: glance
    entities:
      - entity: sun.sun
        name: Sonne
    state_color: true
animation: none
```

**Comment by JonahKr** [comment]
Hey there 👋 
I don't think this is a configuration issue to be fair so it either has to do something with  the rendering, if this card even is the reason for this behaviour. I use the Android app and with that it works totally fine. SInce i have no IOS device, i sadly cannot check this atm. Maybe someone else using an iOS device can help with this? Since nearly 1k people are using the version2.1.1 there has to be someone else using an iOS device.🤔 

The only reason i could think of atm is the ResizeObserver but since this is used in HomeAssistant Frontend aswell you should have experienced some issues already.
Since its crashing in safari aswell(Only mobile/tablet btw?), maybe you are able to take a screenshot of the Console of the browser?
And are you experiencing this since upgrading to a specific version or on a "new" install.


Thanks for reporting anyways and stay safe
Jonah

**Comment by JonahKr** [comment]
additionally @whizkid79 What iOS version are you running? on what kind of device?

**Comment by whizkid79** [comment]
Hi, 
thanks for the tip with trying it on the desktop also in Safari. I get a bit of a different result: First it loads but the center card is not displayed, just an error message instead of the center card. The JS console shows this: 

<img width="1113" alt="Bildschirmfoto 2021-02-26 um 15 59 55" src="https://user-images.githubusercontent.com/14892483/109316887-5b53d380-784c-11eb-9633-1c5885b0af8d.png">

If I reload the browser crashes and I get one message repeatedly in the console. looks like an endless loop to me:
<img width="1106" alt="Bildschirmfoto 2021-02-26 um 16 00 34" src="https://user-images.githubusercontent.com/14892483/109316866-5727b600-784c-11eb-97ce-b27415f90761.png">

I run the App on an iPhone 11 pro with iOS 14.4.

**Comment by JonahKr** [comment]
ok then... lets try a few things if thats ok with you.
uninstall the card and reinstall it (via HACS)? - *this sometimes workes like magic*
then take out the center part completely :
```yaml
center:
  type: card
  content:
    type: glance
    entities:
      - entity: sun.sun
        name: Sonne
    state_color: true
```

and look if its still trowing the setConfig.

I tested your config and it workes completely fine for me. I will see if i find something more...
