### ISSUE TITLE
Is there a possibility to influence the calculation ?

### ISSUE THREAD

**Issue by wowulavega** [JonahKr/power-distribution-card#60]
I have multiple inputs ans want to calculate the effective output to grid.
How can I get access to the calculation ?
Thanks
Wolfgang

**Comment by JonahKr** [comment]
Hey there @wowulavega 👋,

From what i get from your question, you want to include multiple values in the `ratio` and `autarky` calculations.
This is totally possible:
1. You can already exclude the Values from any calculations by ticking the according box under the Preset Settings
2. The Presets define whether sensor values are included in calculations. Each Preset has some predefined flags which you can find in [this file](https://github.com/JonahKr/power-distribution-card/blob/master/src/presets.ts). Internally there are 2 flags: `producer` and `consumer`. All values are summed up accordingly and used for calculations here: https://github.com/JonahKr/power-distribution-card/blob/d455c125bc7fc3939cfd2180d6e99387035d0c2c/src/power-distribution-card.ts#L378-L386 
There are also some specific presets called `consumer` and `producer` to create your own logic.

If that resolves what you meant i am glad i could help. If otherwise, please just further clarify what you want to achieve. (German is fine aswell)

Take Care and Stay Safe! 👍 
Jonah

**Comment by wowulavega** [comment]
Hallo Jonah,
ganz herzlichen Dank für die Antwort, die mir zunächst weitergeholfen hat.
Ich werde mich damit beschäftigen und hoffe, dass ich damit klar komme.
Ich muss dazu sagen, dass ich in das Thema erst einsteige und würde daher gern auf Dein Angebot zurück kommen, wenn ich tatsächlich nicht mehr weiter weiß.
Beste Grüße
Wolfgang

**Comment by JonahKr** [comment]
Klar kein Problem!
Hab gesehen, dass du auch mit Homeassistant an sich ein paar Fragen hattest. Wenn du willst kannst du diesbezüglich auch einfach in diesen Thread deine Fragen oder Probleme reinschreiben und ich werde versuchen, wenn ich Zeit habe, dies bestmöglich zu beantworten.
Ich werde das Issue trotzdem erstmal closen, da es sich bis jetzt ja um kein Spezifisches Problem oder ähnliches handelt.

**Comment by wowulavega** [comment]
Hallo Jonah,
Herzlichen Dank für Dein freundliches Angebot, mir mit Rat zur Seite zu stehen.
Ich möchte es aber nicht überziehen und im Augenblick stehen noch soviel offene Fragen aus, die ich erst allein lösen muss, weil ich Dein Angebot sonst bereits missbraucht hätte.
Eine Frage aber steht wie eine unlösbare Barriere vor mir.
Ich weiss nicht, wie ich CARDS, die ich  im Loveles Frontend geladen habe, nutzbar machen kann denn wenn ich das UI konfigurieren will, erhalte ich immer nur die regulären Standard CARDs, nicht aber die zusätzlich geladenen CARDs.

Wenn Du da einen Tipp hättest, wo wich suchen soll, dann würde mir das helfen.

Die Github Dokumentation hilft mir nicht besonders weiter, weil sie für „Fortgeschrittene“ gemacht ist und keine durchgängige und nachvollziehbare Erklärung beinhaltet.
Was ist sehr darin vermisse ist eine Systemübersicht, die ähnlich einem Flussdiagramm einmal die groben Zusammenhänge der File-Sammelsurien darstellt.
Man muss ich aus den configs mühsam die Referenzen zusammensuchen und kann nur raten, wo sie richtigerweise anzuordnen sind. Das vereinfacht die Sache nicht gerade.
Ich bin nun kein Software-Spezi, weil ich aus der Hardware-Ecke komme … das erschwert die Sache für mich daher.

Aber ganz herzlichen dank nochmal für Dein freundliches Angebot, das ich gern annehme und mich bemühen werde, meine  Fragen tatsächlich auf das Notwendigste zu reduzieren.

Ich lebe übrigens in Südamerika und daher gibt es zu Europa den entsprechenden Zeitunterschied, der manchmal verzögerte Antworten erklärt.

Beste Grüsse
Wolfgang

**Comment by JonahKr** [comment]
Hallo Wolfgang,

Bzgl. der Lovelace Cards:
Das Problem mit sogenannten `custom card`, sprich von der Community erstellte Darstellungen, ist, dass die wenigsten einen UI-Editor mit implementiert haben. Es ist einfach nochmal ein ordentlicher Haufen Arbeit, der sich für die meisten nicht lohnt.
Das gleiche gilt dann für die Einbettung in den sogennanten `Card-Picker`, sprich das Normale Auswahl panel für die Karten über das UI.
Grundsätzlich würde ich daher bei custom-cards eher davon ausgehen, dass sie dort nicht zu finden sind, aber wenn, sind sie mit einem "**Custom:**" gekennzeichnet und ganz unten zu finden.
![image](https://user-images.githubusercontent.com/38377070/112748210-9c114a80-8fba-11eb-97f9-d6cbafd0d137.png)

Falls sie also nicht zu finden sind läuft die Konfiguration eigentlich immer über den Manuellen Weg, sprich mit der Hilfe von YAML. (Hier die Karte `Manual`)

Das Läuft dann eigentlich meistens auch mit dem gleichen Schema:
```yaml
type: 'custom:vertical-stack-in-card'
```
Der `Type` Parameter ist immer notwendig, da dieser die Karte referenziert. Für Custom Cards ist der Name immer `custom:KARTENNAME`.
Die weitere Konfiguration ist dann der jeweiligen Dokumentation zu entnehmen aber zum Beispiel:
```yaml
type: 'custom:vertical-stack-in-card'
cards:
  - entity: sensor.restmull
    hass_lang_priority: true
    type: 'custom:garbage-collection-card'
```

Der Hintergrund des Ganzen, ist das Homeassistant früher nur über YAML konfiguriert wurde, und diese Prozesse in den letzten 1,5 Jahren um das UI erweitert wurden und auch immernoch werden.

Ich hoffe ich konnte dir ein wenig helfen! 👍 

Jonah

**Comment by wowulavega** [comment]
Hallo Jonah,
Danke für den Hinweis.
Ich habe mich mal dran gemacht, den build in eine neue Seite zu integrieren, um mit der Rechnerei einwenig zu experimentieren, bekomme aber einen Error, wie in der Abbildung gezeigt.
Configuration errors detected: 
end of the stream or a document separator is expected at line 36, column 15:
      `font-weight: 500; color: white; background: ... 
                  ^
Kann es sein, dass irgendwo noch ein Whitespace zuviel sitzt ?
Würdest Du einmal einen Blick drauf werfen ?

Darüber hinaus würde ich eine Änderung wie folgt versuchen wollen…

Mehrere Input Sensoren (Solar, Batterie usw.) die addiert eine Summe ergeben (Home Production(Solar, Battery)
Ein oder mehrere Verbraucher, die addiert ebenso eine (negative) Summe ergeben (Home Consumption)

Die Summen addiert ergeben den GRID Anteil, der, je nach den Werten, entweder positiv oder negativ ausfällt.
Wenn sich die Pfeilrichtung nun auch noch nach dem Vorzeichen ausrichtet bekommt man auch eine korrekte Darstellung.
Dieses Additionsergebnis müsste als Entity für das GRID Symbol wirken.

Schafft man dazu noch ein Eingabefeld für die Kosten/kWh ergäbe sich noch ein Betrag, den man in einer späteren Analyse nutzen könnte .

Hättest Du dazu eine Idee ?


Nochmal vielen Dank für Deine Mitwirkung,
Freundliche Grüsse
Wolfgang

**Comment by wowulavega** [comment]
Hallo Jonah

Erst einmal ein frohes Osterfest.

Ich habe aber nocheinmal eine Nachfrage:

Ich kann mit der Errormeldung nichts anfangen.
Configuration errors detected: 
end of the stream or a document separator is expected at line 36, column 15:
      `font-weight: 500; color: white; background: ... 
                  ^
Irgendwo ist da wahrscheinlich ein „space“ zuviel drin.
Aber ich finde es nicht.
Kannst Du den build nochmal mit dem lauffähigen Code abgleichen ?

Besten dank und Gruss
Wolfgang

**Comment by JonahKr** [comment]
Hallo Wolfgang,

Einen angenehmen Ostermontag ersteinmal. 👍 
</br>

> Mehrere Input Sensoren (Solar, Batterie usw.) die addiert eine Summe ergeben (Home Production(Solar, Battery) Ein oder mehrere Verbraucher, die addiert ebenso eine (negative) Summe ergeben (Home Consumption)

Das ist ziemlich deckungsgleich mit der momentanen Implementierung oder nicht? Korregiere mich bitte, wenn ich falsch liege.

> Die Summen addiert ergeben den GRID Anteil, der, je nach den Werten, entweder positiv oder negativ ausfällt. Wenn sich die Pfeilrichtung nun auch noch nach dem Vorzeichen ausrichtet bekommt man auch eine korrekte Darstellung. Dieses Additionsergebnis müsste als Entity für das GRID Symbol wirken.

Du willst quasi das Zuhause als geschlossenes System darstellen und dann den Überschuss / Verbrauch errechnen, richtig?

> Den man in einer späteren Analyse nutzen könnte .

Und hier liegt dann das Problem: Die normalen Schnittstellen für Lovelace Cards sind dafür nicht ausgelegt, sondern nur für die Darstellung von Werten, was auch hinsichtlich der Security definitv Sinn macht. Eine Karte kann auch über normale Wege nicht Werte langfristig speichern und für andere Elemente zugänglich machen.

Das was du, glaube ich zumindest, erreichen willst, lässt sich sehr gut mit einem [Template Sensor](https://www.home-assistant.io/integrations/template/) machen. Dort kann man dann festlegen, wie die Werte verrechnet werden sollen und man konfiguriert quasi einen komplett neuen Sensor in Homeassistant, welcher dann auch überall verfügbar ist.

Das kann dann zum Beispiel so aussehen:
```yaml
sensor:
  - platform: template
    sensors:
      power_home:
        unit_of_measurement: 'W'
        value_template: >-
          {% set consumption = states('sensor.consumer1') + states('sensor.consumer2') %}
          {% set production = states('sensor.prod1') + states('sensor.prod2') %}
          {% consumption + production %}
```
Falls du dich bezüglich der `value_templates` mehr austoben willst, google einfach nach **jinja2**.
<br/><br/>


> Configuration errors detected: end of the stream or a document separator is expected at line 36, column 15: `font-weight: 500; color: white; background: ...

Bezüglich diesen Fehlers kann ich dir leider nicht weiterhelfen. Ich weiß nicht genau, was du verändert hast, oder in welcher Datei du dich überhaupt befindest, welche Sprache (TS, JS, HTML, CSS). Der Ausschnitt, den du hier mitgeschickt hast, ist allerdings valides CSS.

Ich hoffe ich konnte dir einigermaßen helfen! 👍 

Jonah

**Comment by wowulavega** [comment]
﻿
Hallo Jonah,
Ganz herzlichen Dank für die Rückmeldung.
Ich habe jetzt mit Deinem Beispiel versucht, den neuen Wert zu generieren aber komme über eine Fehlermeldung nicht rüber:


Invalid config for [sensor.template]: invalid template (TemplateSyntaxError: Encountered unknown tag 'consumption'.) for dictionary value @ data['sensors']['power_home']['value_template']. Got "{% set consumption = states('sensor.sonoff_10011214ae_power') + states('sensor.sonoff_10009d602d_power') %} {% set production = states('sensor.sonoff_10005114c0_power') + states('sensor.sonoff_1000051308_power') %} {% consumption + production %}". (See ?, line ?).

Ich habe eigentlich nur die Sensoren ersetzt (oder gehören da die „friendly names“ rein )

# configuration.yaml entry POWER CONSUMPTION

  - platform: template
    sensors:
      power_home:
        unit_of_measurement: 'W'
        value_template: >-
          {% set consumption = states('sensor.sonoff_10011214ae_power') + states('sensor.sonoff_10009d602d_power') %}
          {% set production = states('sensor.sonoff_10005114c0_power') + states('sensor.sonoff_1000051308_power') %}
          {% consumption + production %}


Aber im Prinzip habe ich das jetzt verstanden und ich habe aus dem verlinkten Text mal das „Sonnen- template“ eingefügt, das lief einwandfrei.
Ich denke also, ich habe mit der Eingabe der Sensoren irgend welchen Mist gebaut.
Danke für einen kurzen Hinweis.

Gruss
Wolfgang

**Comment by JonahKr** [comment]
Hallo Wolfgang,
Ja mir ist bei der `value template` ein kleiner Fehler unterlaufen.
Damit sollte es bei dir funktionieren:
```yaml
  - platform: template
    sensors:
      power_home:
        unit_of_measurement: 'W'
        value_template: >-
          {% set consumption = (states('sensor.sonoff_10011214ae_power') |float) + (states('sensor.sonoff_10009d602d_power') |float) %}
          {% set production = (states('sensor.sonoff_10005114c0_power') |float) + (states('sensor.sonoff_1000051308_power') |float) %}
          {{ consumption + production }}
```

Der Erste Fehler, der mir unterlaufen ist, war, dass die `states` methode text und keine Zahl zurück gibt.
Das zweite war, dass ich anstatt als Ausgabe die letzte Zeile als Ausdruck / Operation definiert habe. (durch {% anstatt {{ )

Gruss,

Jonah

**Comment by wowulavega** [comment]
Hmmm 
leider nicht 😩

**Comment by wowulavega** [comment]
Da hatte ich noch ein „sensors“ drin stehen, das hab ich jetzt mal rausgenommen, bekomme dafür einen andern Fehler

**Comment by JonahKr** [comment]
Ich hab die Korregierte version nochmal bei mir getestet und sie funktioniert einwandfrei. 🤔 
Kannst du deinen Fehler hier einfach nochmal reinschicken?

**Comment by wowulavega** [comment]
Hallo Jonah,
klappt leider nicht...
Selbe Fehlermeldung. Leider sagt sie mir, als Anfänger nichts.
Ich hab auch nochmal das Template aus dem Beispiel eingefügt, um zusehen, ob ich irgendwelche grundsätzlichen Probleme in meinem „config“ habe aber das funktioniert.

**Comment by JonahKr** [comment]
kannst du einmal das komplette file reinschicken, damit ich vielleicht den Fehler finden kann?

**Comment by wowulavega** [comment]
Hallo Jonah,
Sorry für die Verspätung aber hier nun der Link zur File-Kopie

https://www.dropbox.com/s/jrtvpi7in73ndnu/configuration%20kopie.yaml?dl=0 <https://www.dropbox.com/s/jrtvpi7in73ndnu/configuration%20kopie.yaml?dl=0>


Danke für Deine Mühe.
Gruss
Wolfgang

**Comment by JonahKr** [comment]
Hallo Wolfgang.
Der Fehelr liegt hier in Zeile 57.
Das `sensors:` müsste auskommentiert werden.
```yaml
      sunrise:
        value_template: "{{ state_attr('sun.sun', 'next_rising') }}"
      power_home:
        unit_of_measurement: 'W'
        value_template: >-
          {% set consumption = (states('sensor.sonoff_10011214ae_power') |float) + (states('sensor.sonoff_10009d602d_power') |float) %}
          {% set production = (states('sensor.sonoff_10005114c0_power') |float) + (states('sensor.sonoff_1000051308_power') |float) %}
          {{ consumption + production }}
          
```

So sollte es dann ab Zeile 50 aussehen
