### ISSUE TITLE
Calculating and Visualizing Home Consumption

### ISSUE THREAD

**Issue by martymoose** [JonahKr/power-distribution-card#70]
Hi where I am we are a net solar house
So our power is used first then exported
I have a shelly the monitors solar output and another that measures the utility in or out power
How hard would it be to put a equation it there so with the display it would be on left I have my output/input  to grid. On right my solar output
In the middle where you have the %
I would to to have a total of solar - power = what my house is consuming
IE: I am producing 5000ww and outputing to grid 4700w so my house is using 300 which would fit inbetween left and right icon
Cheers and love this card

**Comment by wowulavega** [comment]
@martimoosy
I’ve mad a calculation like this in the software.
It works fine for me and shows me 2 different solar sources, the result solar, the house consumption pet phase (2x 110V split phase) and the remaining going into the Grid.
Therefore I have 4 sonoff sensors in use.
If that would help you, let me know.

**Comment by JonahKr** [comment]
Hey there @martymoose 👋 
This is a lovelace card so no equations can be solved using it. **However:**
You could create a custom sensor in Homeassistant like this:
```yaml
 - platform: template
    sensors:
      home_consumption:
        unit_of_measurement: 'W'
        value_template: '{{ ((states('sensor.SOLAR_SENSOR') |float) + (states('sensor.GRID_SENSOR') |float)) * -1 }}'
```
This is assuming your Solar Sensor ONLY outputs positive Numbers and your Grid Sensor returns negative numbers for exporting and positive for consuming!

After this you can just add it like a custom card in the middle: https://github.com/JonahKr/power-distribution-card#cards-

Let me know if that works for you and stay safe 👍 
Jonah
