### ISSUE TITLE
Add battery status (charged percentage)

### ISSUE THREAD

**Issue by saunameister** [JonahKr/power-distribution-card#78]
Idea to extend the card is show the status of the battery (charged percentage)

Two ideas:
1. icon battery without the animation
2. horizontal bar below the center

**Comment by JonahKr** [comment]
Hey there @saunameister 👋 

I think the first one can already be done: 
![image](https://user-images.githubusercontent.com/38377070/127129774-ec548bbb-9da5-44b6-855b-dc25412e6480.png)

```yaml
center:
  type: card
  content:
    type: entity
    icon: mdi:battery-outline
    name: battery
    entity: sensor.battery_percentage
```

For the second one i am not really sure what you mean.
Do you mean something like this?
![image](https://user-images.githubusercontent.com/38377070/127130519-88ed6e7b-55c0-4e84-a625-645e8208ad0a.png)

For this you can use the bar-card and vertical-stack-in card.

Let me know if thats what you meant.

Take care and stay safe! 👍 

Jonah
