### ISSUE TITLE
Lost my autarky & ratio

### ISSUE THREAD

**Issue by TheLordVader** [JonahKr/power-distribution-card#89]
Hi, love your custom card!

I have been struggling with some problems with Solaredge modbus sensors lately (solved now), and now my autarky and ratio are gone. I can't figure out whats wrong and need som assistance please...
```yaml
type: vertical-stack
cards:
  - type: energy-distribution
    link_dashboard: true
  - type: custom:power-distribution-card
    title: Power distribution
    entities:
      - decimals: 2
        display_abs: true
        name: grid
        unit_of_display: W
        icon: mdi:transmission-tower
        entity: sensor.solaredge_m1_ac_power
        preset: grid
      - decimals: 2
        display_abs: true
        name: solar
        unit_of_display: W
        icon: mdi:solar-power
        producer: true
        entity: sensor.solaredge_ac_power
        preset: solar
      - decimals: '0'
        display_abs: true
        name: TH
        unit_of_display: W
        consumer: true
        icon: mdi:home
        entity: sensor.th_total_power
        preset: consumer
        threshold: ''
        icon_color:
          bigger: ''
          equal: ''
          smaller: ''
        calc_excluded: true
        invert_value: false
        invert_arrow: true
      - decimals: 2
        display_abs: true
        name: BV
        unit_of_display: W
        consumer: true
        icon: mdi:radiator
        entity: sensor.bv_total_power
        preset: consumer
        threshold: ''
        icon_color:
          bigger: ''
          equal: ''
          smaller: ''
        calc_excluded: true
        invert_value: false
        invert_arrow: true
      - decimals: 2
        display_abs: true
        name: HD
        unit_of_display: W
        consumer: true
        icon: mdi:home
        entity: sensor.hd_total_power
        preset: consumer
        threshold: ''
        icon_color:
          bigger: ''
          equal: ''
          smaller: ''
        calc_excluded: true
        invert_value: false
        invert_arrow: true
    center:
      type: bars
      content:
        - preset: autarky
          name: autarky
          bar_bg_color: red
          bar_color: green
        - preset: ratio
          name: ratio
          bar_bg_color: red
          bar_color: green
    animation: slide
```
