### ISSUE TITLE
Battery SoC not shown

### ISSUE THREAD

**Issue by Xrlwyzz** [JonahKr/power-distribution-card#92]
Hi,

first of all, thank you for the great work!

I cannot find any error in my configuration, but the battery soc is not displayed. It looks like this:
![grafik](https://user-images.githubusercontent.com/93951207/144431510-42e30a91-1481-4a74-a5d0-303827a7880a.png)

The sensor "sensor.battery_soc_total" is working as expected:
![grafik](https://user-images.githubusercontent.com/93951207/144431839-22282dbe-d9f3-412f-ae13-823ff206f20d.png)

My configuration:
```yaml
type: custom:power-distribution-card
title: Power distribution
entities:
  - decimals: '0'
    display_abs: true
    name: PV
    unit_of_display: W
    icon: mdi:solar-power
    producer: true
    entity: sensor.gesamtleistung_pv
    preset: solar
  - decimals: 2
    display_abs: true
    name: Battery
    unit_of_display: W
    consumer: true
    icon: mdi:battery-outline
    producer: true
    entity: sensor.grid_power_2
    preset: battery
    battery_percentage_entity: sensor.battery_soc_total
  - decimals: '0'
    display_abs: true
    name: Grid
    unit_of_display: W
    icon: mdi:transmission-tower
    entity: sensor.metering_power_absorbed
    preset: grid
    grid_buy_entity: sensor.metering_total_absorbed
    grid_sell_entity: sensor.metering_total_yield
  - decimals: 2
    display_abs: true
    name: Home
    unit_of_display: W
    consumer: true
    icon: mdi:home-assistant
    entity: sensor.hausverbrauch
    preset: home
    invert_value: true
center:
  type: bars
  content:
    - preset: autarky
      name: Autarkie
    - preset: ratio
      name: Anteil
animation: flash
```
And a request for improvement: I hopefully will be able to help myself with a template - but in my case values like power delivered to the grid and taken form the grid are delivered by the inverter in different values (SMA components by the way). It would make things easier if I also had the option to simply add the two sensors I already have
