### ISSUE TITLE
Grid delivery/returned power into 1 item

### ISSUE THREAD

**Issue by johanvh83** [JonahKr/power-distribution-card#93]
Hi,
First of all: You did a great job by making this card. It's so usefull! This lovelace card was really something I was looking for.
There is 1 thing I'd like to improve:

From my grid I get 2 entities: sensor_power_delivered and sensor_power _returned, both give positive values.
I searched how to get both entities into 1 grid-'symbol', but can't find how to setup.
I've seen that the Card Configuration has optional Grid Buy and Grid Sell fields and when I fill them with the above entities I get extra information in the Grid icon but the arrow that animated the power flow only works in 1 direction for the Entity used in the Entity (Required) field:
![image](https://user-images.githubusercontent.com/76775686/145403267-df360be4-d64f-4ade-b21c-b95fcd307c36.png)

The 'work-around' I found is to use 2 Entities:
![image](https://user-images.githubusercontent.com/76775686/145402673-9d4a384d-4453-4446-a1b4-0926e3a7e9ce.png)
The sensor_power_returned entity gives me positive values but by using 'invert value' it works as it should be and when power returned the animation works correctly.
It would be nice if I could combine it into 1 symbol.

**Thanks for your time and support!**

If usefull this is my card configuration:
```yaml
type: custom:power-distribution-card
title: ''
entities:
  - decimals: 2
    display_abs: true
    name: solar
    unit_of_display: W
    icon: mdi:solar-power
    producer: true
    entity: sensor.pv_actuele_opbrengst
    preset: solar
    threshold: ''
    icon_color:
      bigger: green
      equal: ''
      smaller: ''
    calc_excluded: false
  - decimals: 2
    display_abs: true
    name: Grid delivery
    unit_of_display: W
    icon: mdi:transmission-tower
    entity: sensor.power_delivered
    preset: grid
    threshold: ''
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    grid_buy_entity: ''
    grid_sell_entity: ''
    hide_arrows: false
  - decimals: 2
    display_abs: true
    name: Batterij
    unit_of_display: W
    consumer: true
    icon: mdi:battery-outline
    producer: true
    entity: sensor.storage_charge_discharge_power_hv2180152184
    preset: battery
    invert_value: true
    threshold: ''
    icon_color:
      equal: ''
    secondary_info_entity: sensor.pv_batt_capacity
    battery_percentage_entity: sensor.pv_batt_capacity
    hide_arrows: false
  - decimals: 2
    display_abs: true
    name: Grid returned
    unit_of_display: W
    icon: mdi:transmission-tower
    entity: sensor.power_returned
    preset: grid
    threshold: ''
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    invert_value: true
  - decimals: 2
    display_abs: true
    name: Huis
    unit_of_display: W
    consumer: true
    icon: mdi:home
    invert_value: true
    entity: sensor.sun2000_4_6ktl_l1_hv2180152184
    preset: home
center:
  type: bars
  content:
    - preset: autarky
      name: Home
    - preset: ratio
      name: Ratio
animation: slide
```

**Comment by JonahKr** [comment]
Hey there @johanvh83 👋 
Glad you like the card.
Regarding your feature Request: (References: #92 )
I like the idea, however I have come to a point where the visual editor is already somewhat overloaded and the codebase gets more and more nested/messy to keep all features working together.
Especially in this case, there are just to many possible ways of of combining multiple sensors that I would rather leave that to the user than try to offer a conclusive palette of options.
Additionally home assistant offers a easy workaround for such cases: [Template Sensors](https://www.home-assistant.io/integrations/template/)
Let me know if i can help you with this!

Take care and stay safe! 👍 
Jonah

**Comment by johanvh83** [comment]
Hi Jonah,

I'm not a programmer / coder, so I'm afraid I need some help
My 2 entities are:
sensor.power_delivered
sensor.power_returned

As explained both give positive values. If you can do a magic trick to
combine both entities into 1 entity with positive (delivered) and negative
(returned) values, that would be great.

Thanks a lot!
Johan

Op zo 12 dec. 2021 om 22:01 schreef JonahKr ***@***.***>:

**Comment by JonahKr** [comment]
Hi @johanvh83,

Assuming that only one of the values will ever be bigger than 0, you could achieve this with something like:
```yaml
power_grid:
    unit_of_measurement: 'W'
    value_template: >-
        {% set delivered = states('sensor.power_delivered') |float)  %}
        {% set returned = states('sensor.power_returned') |float)  %}
        {{ delivered- returned }}
```

**Comment by johanvh83** [comment]
Hi Jonah,

Spend already 1 hour to implement the code but always get errors when
I check my configuration.

So my configuration.yaml is:

template:
  - sensor:
    - name: "power_distri"
      unit_of_measurement: "W"
      state: >
        {% set delivered = states('sensor.power_delivered') | float) %}
        {% set returned = states('sensor.power_returned') | float) %}
        {{ delivered- returned }}

I thought the last line was incorrect; there is no space between
'delivered' and minus '-'.
So I changed to 'delivered - returned' instead of 'delivered-
returned) but it's not a solution.

Based on https://www.home-assistant.io/integrations/template/ I tried
{{ (delivered- returned) }} but no luck...

I'm a bit despirate...

Could you help me?
Thanks in advance

Johan
Op zo 12 dec. 2021 om 22:48 schreef JonahKr ***@***.***>:

**Comment by JonahKr** [comment]
Hey there 👋 @johanvh83 
I'm sorry i missed a closing braket in my example -_-.
Here is a shorter Version i tested to be sure it works:
```yaml
template:
  - sensor:
      - name: 'power_distri'
        unit_of_measurement: "W"
        state: "{{ (states('sensor.power_delivered') |float) - (states('sensor.power_returned') |float) }}"
```
