### ISSUE TITLE
Secondary info display not working?

### ISSUE THREAD

**Issue by mdoliver** [JonahKr/power-distribution-card#94]
Hi,

Bit of an HA newbie here. I have this card working for the most part, in the way I'd like. I'm just trying to get one of the preset consumer entries to display an additional status string. The status is held in entity ID: sensor.myenergi_eddi_energy_diverter_status. 

1. When I add this as a secondary attribute to the preset consumer entry for "Eddi" I get the following displayed (screen capture1) 
2. When I add the sensor as its own preset producer entry for "hydro-power" I see nothing (screen capture 2)
3. And when I add the sensor as a normal glance card (screen capture 3)

Screen capture 1
![image](https://user-images.githubusercontent.com/51429339/146291762-8270a0d4-0e07-4376-8cca-d01bba9485a1.png)

Screen capture 2
![image](https://user-images.githubusercontent.com/51429339/146293538-5361adf3-9cdd-499f-9108-0df23347bf9d.png)

Screen capture 3
![image](https://user-images.githubusercontent.com/51429339/146294500-2d2e623a-8f02-43bb-83ae-cbb23fa711cc.png)

Here's my setup. Where am I going wrong?

Custom Power Distribution Card code
--
```yaml
type: custom:power-distribution-card
title: ''
entities:
    decimals: '1'
    display_abs: true
    name: solar
    unit_of_display: kW
    icon: mdi:solar-panel-large
    producer: true
    entity: sensor.myenergi_eddi_hub_power_generation
    preset: solar
    threshold: '50'
    icon_color:
      bigger: Green
      equal: ''
      smaller: ''
    attribute: ''
    decimals: '1'
    display_abs: true
    name: grid
    unit_of_display: kW
    icon: mdi:transmission-tower
    entity: sensor.myenergi_eddi_hub_power_import
    preset: grid
    threshold: ''
    icon_color:
      bigger: Red
      equal: ''
      smaller: ''
    decimals: '1'
    display_abs: true
    name: Eddi
    unit_of_display: kW
    consumer: true
    icon: mdi:shower-head
    entity: sensor.myenergi_eddi_hub_power_charging
    preset: consumer
    threshold: ''
    icon_color:
      equal: ''
      smaller: Green
      bigger: ''
    invert_value: true
    secondary_info_entity: sensor.myenergi_eddi_energy_diverter_status
    secondary_info_attribute: ''
    decimals: '1'
    display_abs: true
    name: grid
    unit_of_display: kW
    icon: mdi:transmission-tower
    entity: sensor.myenergi_eddi_hub_power_export
    preset: grid
    threshold: ''
    icon_color:
      bigger: Green
      equal: ''
      smaller: ''
    decimals: 2
    display_abs: true
    name: ''
    unit_of_display: W
    icon: mdi:hydro-power
    producer: true
    entity: sensor.myenergi_eddi_energy_diverter_status
    preset: hydro
    threshold: ''
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
center:
  type: card
  content:
    type: glance
    entities:
        sensor.myenergi_eddi_hub_home_consumption
    show_name: true
animation: slide
```

Normal glance card code:
--
```yaml
type: glance
entities:
    entity: sensor.myenergi_eddi_energy_diverter_status
```
