### ISSUE TITLE
Battery % not visible

### ISSUE THREAD

**Issue by Spookster** [JonahKr/power-distribution-card#95]
Hi, love your work. 
Ive noticed the placement of the battery percentage (secondary info) covers the icon making it hard to read.
Especially when in the format xx.x%
I can recolor the icon to make it more visible, but cant move it?
Would it be possible to perhaps select Name(optional) or Battery percent to clean up the display of that icon?

![image](https://user-images.githubusercontent.com/982535/147971977-8b07c292-b0c6-4fef-ae90-a2223cd626db.png)
```yaml
_entity: sensor.solar_battery_i_o
    preset: battery
    icon: mdi:battery-outline
    threshold: '10'
    icon_color:
      bigger: pink
      equal: white
      smaller: green
    secondary_info_entity: sensor.solar_battery_soc
    secondary_info_attribute: ''
    battery_percentage_entity: sensor.solar_battery_soc
    attribute: ''
  - decimals: '0'
    display_abs: true_
```
