### ISSUE TITLE
Secondary info string appends "Undefined"

### ISSUE THREAD

**Issue by mdoliver** [JonahKr/power-distribution-card#99]
Hi,

Thanks for the update, great work!

I'm trying to get the secondary info display with replace name option, to work properly. For the most part it works well, however any entity I use for the secondary info section not only displays the string value of that entity but also appends "Undefined" to it as well (see screen capture)

I've tried this with random other entities that contain a text string and they all append "Undefined" to the the display

![image](https://user-images.githubusercontent.com/51429339/149404572-a23b2fbb-f9d4-433f-a0b1-b89a367feb07.png)

My section of code for this sensor

```
 -  decimals: 2
    display_abs: true
    name: consumer
    unit_of_display: W
    icon: mdi:shower-head
    consumer: true
    entity: sensor.myenergi_eddi_hub_power_charging
    preset: consumer
    color_threshold: '0'
    threshold: ''
    icon_color:
      bigger: ''
      equal: ''
      smaller: ''
    arrow_color:
      bigger: ''
      equal: ''
      smaller: ''
    secondary_info_entity: sensor.myenergi_eddi_energy_diverter_status
    secondary_info_replace_name: true
```
